spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Demonstrates outbound HTTP calls"
name = "spin-outbound-post"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "spin-outbound-post"

[component.spin-outbound-post]
source = "target/wasm32-wasi/release/spin_outbound_post.wasm"
allowed_outbound_hosts = ["http://*:*", "https://*:*"]
[component.spin-outbound-post.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
