use * from pg-types
use * from rdbms-types

// query the database: select
query: func(address: string, statement: string, params: list<parameter-value>) -> result<row-set, pg-error>

// execute command to the database: insert, update, delete
execute: func(address: string, statement: string, params: list<parameter-value>) -> result<u64, pg-error>
