[package]
name = "spin-trigger"
version = "0.2.0"
edition = "2021"
authors = ["mossaka <duibao55328@gmail.com>"]

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.1.15", features = ["derive", "env"] }
ctrlc = { version = "3.2", features = ["termination"] }
futures = "0.3"
http = "0.2"
outbound-redis = { path = "../outbound-redis" }
serde = "1.0"
spin-config = { path = "../config" }
spin-engine = { path = "../engine" }
spin-loader = { path = "../loader" }
spin-manifest = { path = "../manifest" }
tracing = { version = "0.1", features = [ "log" ] }
wasi-outbound-http = { path = "../outbound-http" } 
wasmtime = "0.38.0"
